package neu.train.project.mvo.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class ManManufacturer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.man_id
     *
     * @mbg.generated
     */
    private Integer manId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.sys_user_id
     *
     * @mbg.generated
     */
    private Integer sysUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.name_en
     *
     * @mbg.generated
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.name_cn
     *
     * @mbg.generated
     */
    private String nameCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.gmc_report_type
     *
     * @mbg.generated
     */
    private String gmcReportType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.gmc_report_url
     *
     * @mbg.generated
     */
    private String gmcReportUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.last_update_by
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.last_update_time
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.call_cnt
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.sts_cd
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_manufacturer.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.man_id
     *
     * @return the value of man_manufacturer.man_id
     *
     * @mbg.generated
     */
    public Integer getManId() {
        return manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.man_id
     *
     * @param manId the value for man_manufacturer.man_id
     *
     * @mbg.generated
     */
    public void setManId(Integer manId) {
        this.manId = manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.sys_user_id
     *
     * @return the value of man_manufacturer.sys_user_id
     *
     * @mbg.generated
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.sys_user_id
     *
     * @param sysUserId the value for man_manufacturer.sys_user_id
     *
     * @mbg.generated
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.name_en
     *
     * @return the value of man_manufacturer.name_en
     *
     * @mbg.generated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.name_en
     *
     * @param nameEn the value for man_manufacturer.name_en
     *
     * @mbg.generated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.name_cn
     *
     * @return the value of man_manufacturer.name_cn
     *
     * @mbg.generated
     */
    public String getNameCn() {
        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.name_cn
     *
     * @param nameCn the value for man_manufacturer.name_cn
     *
     * @mbg.generated
     */
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.gmc_report_type
     *
     * @return the value of man_manufacturer.gmc_report_type
     *
     * @mbg.generated
     */
    public String getGmcReportType() {
        return gmcReportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.gmc_report_type
     *
     * @param gmcReportType the value for man_manufacturer.gmc_report_type
     *
     * @mbg.generated
     */
    public void setGmcReportType(String gmcReportType) {
        this.gmcReportType = gmcReportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.gmc_report_url
     *
     * @return the value of man_manufacturer.gmc_report_url
     *
     * @mbg.generated
     */
    public String getGmcReportUrl() {
        return gmcReportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.gmc_report_url
     *
     * @param gmcReportUrl the value for man_manufacturer.gmc_report_url
     *
     * @mbg.generated
     */
    public void setGmcReportUrl(String gmcReportUrl) {
        this.gmcReportUrl = gmcReportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.created_by
     *
     * @return the value of man_manufacturer.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.created_by
     *
     * @param createdBy the value for man_manufacturer.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.create_time
     *
     * @return the value of man_manufacturer.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.create_time
     *
     * @param createTime the value for man_manufacturer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.last_update_by
     *
     * @return the value of man_manufacturer.last_update_by
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.last_update_by
     *
     * @param lastUpdateBy the value for man_manufacturer.last_update_by
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.last_update_time
     *
     * @return the value of man_manufacturer.last_update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.last_update_time
     *
     * @param lastUpdateTime the value for man_manufacturer.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(LocalDateTime lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.call_cnt
     *
     * @return the value of man_manufacturer.call_cnt
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.call_cnt
     *
     * @param callCnt the value for man_manufacturer.call_cnt
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.sts_cd
     *
     * @return the value of man_manufacturer.sts_cd
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.sts_cd
     *
     * @param stsCd the value for man_manufacturer.sts_cd
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_manufacturer.description
     *
     * @return the value of man_manufacturer.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_manufacturer.description
     *
     * @param description the value for man_manufacturer.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", manId=").append(manId);
        sb.append(", sysUserId=").append(sysUserId);
        sb.append(", nameEn=").append(nameEn);
        sb.append(", nameCn=").append(nameCn);
        sb.append(", gmcReportType=").append(gmcReportType);
        sb.append(", gmcReportUrl=").append(gmcReportUrl);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateBy=").append(lastUpdateBy);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", callCnt=").append(callCnt);
        sb.append(", stsCd=").append(stsCd);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ManManufacturer other = (ManManufacturer) that;
        return (this.getManId() == null ? other.getManId() == null : this.getManId().equals(other.getManId()))
            && (this.getSysUserId() == null ? other.getSysUserId() == null : this.getSysUserId().equals(other.getSysUserId()))
            && (this.getNameEn() == null ? other.getNameEn() == null : this.getNameEn().equals(other.getNameEn()))
            && (this.getNameCn() == null ? other.getNameCn() == null : this.getNameCn().equals(other.getNameCn()))
            && (this.getGmcReportType() == null ? other.getGmcReportType() == null : this.getGmcReportType().equals(other.getGmcReportType()))
            && (this.getGmcReportUrl() == null ? other.getGmcReportUrl() == null : this.getGmcReportUrl().equals(other.getGmcReportUrl()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastUpdateBy() == null ? other.getLastUpdateBy() == null : this.getLastUpdateBy().equals(other.getLastUpdateBy()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getCallCnt() == null ? other.getCallCnt() == null : this.getCallCnt().equals(other.getCallCnt()))
            && (this.getStsCd() == null ? other.getStsCd() == null : this.getStsCd().equals(other.getStsCd()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getManId() == null) ? 0 : getManId().hashCode());
        result = prime * result + ((getSysUserId() == null) ? 0 : getSysUserId().hashCode());
        result = prime * result + ((getNameEn() == null) ? 0 : getNameEn().hashCode());
        result = prime * result + ((getNameCn() == null) ? 0 : getNameCn().hashCode());
        result = prime * result + ((getGmcReportType() == null) ? 0 : getGmcReportType().hashCode());
        result = prime * result + ((getGmcReportUrl() == null) ? 0 : getGmcReportUrl().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastUpdateBy() == null) ? 0 : getLastUpdateBy().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getCallCnt() == null) ? 0 : getCallCnt().hashCode());
        result = prime * result + ((getStsCd() == null) ? 0 : getStsCd().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public enum Column {
        manId("man_id", "manId", "INTEGER", false),
        sysUserId("sys_user_id", "sysUserId", "INTEGER", false),
        nameEn("name_en", "nameEn", "VARCHAR", false),
        nameCn("name_cn", "nameCn", "VARCHAR", false),
        gmcReportType("gmc_report_type", "gmcReportType", "VARCHAR", false),
        gmcReportUrl("gmc_report_url", "gmcReportUrl", "VARCHAR", false),
        createdBy("created_by", "createdBy", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        lastUpdateBy("last_update_by", "lastUpdateBy", "VARCHAR", false),
        lastUpdateTime("last_update_time", "lastUpdateTime", "TIMESTAMP", false),
        callCnt("call_cnt", "callCnt", "INTEGER", false),
        stsCd("sts_cd", "stsCd", "CHAR", false),
        description("description", "description", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}