package neu.train.project.mvo.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ManManufacturerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public ManManufacturerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public ManManufacturerExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public ManManufacturerExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        ManManufacturerExample example = new ManManufacturerExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public ManManufacturerExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public ManManufacturerExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andManIdIsNull() {
            addCriterion("man_id is null");
            return (Criteria) this;
        }

        public Criteria andManIdIsNotNull() {
            addCriterion("man_id is not null");
            return (Criteria) this;
        }

        public Criteria andManIdEqualTo(Integer value) {
            addCriterion("man_id =", value, "manId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andManIdEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("man_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andManIdNotEqualTo(Integer value) {
            addCriterion("man_id <>", value, "manId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andManIdNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("man_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andManIdGreaterThan(Integer value) {
            addCriterion("man_id >", value, "manId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andManIdGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("man_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andManIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("man_id >=", value, "manId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andManIdGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("man_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andManIdLessThan(Integer value) {
            addCriterion("man_id <", value, "manId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andManIdLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("man_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andManIdLessThanOrEqualTo(Integer value) {
            addCriterion("man_id <=", value, "manId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andManIdLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("man_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andManIdIn(List<Integer> values) {
            addCriterion("man_id in", values, "manId");
            return (Criteria) this;
        }

        public Criteria andManIdNotIn(List<Integer> values) {
            addCriterion("man_id not in", values, "manId");
            return (Criteria) this;
        }

        public Criteria andManIdBetween(Integer value1, Integer value2) {
            addCriterion("man_id between", value1, value2, "manId");
            return (Criteria) this;
        }

        public Criteria andManIdNotBetween(Integer value1, Integer value2) {
            addCriterion("man_id not between", value1, value2, "manId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNull() {
            addCriterion("sys_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNotNull() {
            addCriterion("sys_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdEqualTo(Integer value) {
            addCriterion("sys_user_id =", value, "sysUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andSysUserIdEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sys_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotEqualTo(Integer value) {
            addCriterion("sys_user_id <>", value, "sysUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andSysUserIdNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sys_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThan(Integer value) {
            addCriterion("sys_user_id >", value, "sysUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andSysUserIdGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sys_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_user_id >=", value, "sysUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andSysUserIdGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sys_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThan(Integer value) {
            addCriterion("sys_user_id <", value, "sysUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andSysUserIdLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sys_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("sys_user_id <=", value, "sysUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andSysUserIdLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sys_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysUserIdIn(List<Integer> values) {
            addCriterion("sys_user_id in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotIn(List<Integer> values) {
            addCriterion("sys_user_id not in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdBetween(Integer value1, Integer value2) {
            addCriterion("sys_user_id between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_user_id not between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andNameEnIsNull() {
            addCriterion("name_en is null");
            return (Criteria) this;
        }

        public Criteria andNameEnIsNotNull() {
            addCriterion("name_en is not null");
            return (Criteria) this;
        }

        public Criteria andNameEnEqualTo(String value) {
            addCriterion("name_en =", value, "nameEn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameEnEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_en = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameEnNotEqualTo(String value) {
            addCriterion("name_en <>", value, "nameEn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameEnNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_en <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameEnGreaterThan(String value) {
            addCriterion("name_en >", value, "nameEn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameEnGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_en > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("name_en >=", value, "nameEn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameEnGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_en >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameEnLessThan(String value) {
            addCriterion("name_en <", value, "nameEn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameEnLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_en < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameEnLessThanOrEqualTo(String value) {
            addCriterion("name_en <=", value, "nameEn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameEnLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_en <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameEnLike(String value) {
            addCriterion("name_en like", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnNotLike(String value) {
            addCriterion("name_en not like", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnIn(List<String> values) {
            addCriterion("name_en in", values, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnNotIn(List<String> values) {
            addCriterion("name_en not in", values, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnBetween(String value1, String value2) {
            addCriterion("name_en between", value1, value2, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnNotBetween(String value1, String value2) {
            addCriterion("name_en not between", value1, value2, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameCnIsNull() {
            addCriterion("name_cn is null");
            return (Criteria) this;
        }

        public Criteria andNameCnIsNotNull() {
            addCriterion("name_cn is not null");
            return (Criteria) this;
        }

        public Criteria andNameCnEqualTo(String value) {
            addCriterion("name_cn =", value, "nameCn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameCnEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_cn = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameCnNotEqualTo(String value) {
            addCriterion("name_cn <>", value, "nameCn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameCnNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_cn <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameCnGreaterThan(String value) {
            addCriterion("name_cn >", value, "nameCn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameCnGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_cn > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameCnGreaterThanOrEqualTo(String value) {
            addCriterion("name_cn >=", value, "nameCn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameCnGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_cn >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameCnLessThan(String value) {
            addCriterion("name_cn <", value, "nameCn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameCnLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_cn < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameCnLessThanOrEqualTo(String value) {
            addCriterion("name_cn <=", value, "nameCn");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andNameCnLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("name_cn <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNameCnLike(String value) {
            addCriterion("name_cn like", value, "nameCn");
            return (Criteria) this;
        }

        public Criteria andNameCnNotLike(String value) {
            addCriterion("name_cn not like", value, "nameCn");
            return (Criteria) this;
        }

        public Criteria andNameCnIn(List<String> values) {
            addCriterion("name_cn in", values, "nameCn");
            return (Criteria) this;
        }

        public Criteria andNameCnNotIn(List<String> values) {
            addCriterion("name_cn not in", values, "nameCn");
            return (Criteria) this;
        }

        public Criteria andNameCnBetween(String value1, String value2) {
            addCriterion("name_cn between", value1, value2, "nameCn");
            return (Criteria) this;
        }

        public Criteria andNameCnNotBetween(String value1, String value2) {
            addCriterion("name_cn not between", value1, value2, "nameCn");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeIsNull() {
            addCriterion("gmc_report_type is null");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeIsNotNull() {
            addCriterion("gmc_report_type is not null");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeEqualTo(String value) {
            addCriterion("gmc_report_type =", value, "gmcReportType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportTypeEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeNotEqualTo(String value) {
            addCriterion("gmc_report_type <>", value, "gmcReportType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportTypeNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeGreaterThan(String value) {
            addCriterion("gmc_report_type >", value, "gmcReportType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportTypeGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeGreaterThanOrEqualTo(String value) {
            addCriterion("gmc_report_type >=", value, "gmcReportType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportTypeGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeLessThan(String value) {
            addCriterion("gmc_report_type <", value, "gmcReportType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportTypeLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeLessThanOrEqualTo(String value) {
            addCriterion("gmc_report_type <=", value, "gmcReportType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportTypeLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeLike(String value) {
            addCriterion("gmc_report_type like", value, "gmcReportType");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeNotLike(String value) {
            addCriterion("gmc_report_type not like", value, "gmcReportType");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeIn(List<String> values) {
            addCriterion("gmc_report_type in", values, "gmcReportType");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeNotIn(List<String> values) {
            addCriterion("gmc_report_type not in", values, "gmcReportType");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeBetween(String value1, String value2) {
            addCriterion("gmc_report_type between", value1, value2, "gmcReportType");
            return (Criteria) this;
        }

        public Criteria andGmcReportTypeNotBetween(String value1, String value2) {
            addCriterion("gmc_report_type not between", value1, value2, "gmcReportType");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlIsNull() {
            addCriterion("gmc_report_url is null");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlIsNotNull() {
            addCriterion("gmc_report_url is not null");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlEqualTo(String value) {
            addCriterion("gmc_report_url =", value, "gmcReportUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportUrlEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_url = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlNotEqualTo(String value) {
            addCriterion("gmc_report_url <>", value, "gmcReportUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportUrlNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_url <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlGreaterThan(String value) {
            addCriterion("gmc_report_url >", value, "gmcReportUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportUrlGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_url > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlGreaterThanOrEqualTo(String value) {
            addCriterion("gmc_report_url >=", value, "gmcReportUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportUrlGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_url >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlLessThan(String value) {
            addCriterion("gmc_report_url <", value, "gmcReportUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportUrlLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_url < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlLessThanOrEqualTo(String value) {
            addCriterion("gmc_report_url <=", value, "gmcReportUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andGmcReportUrlLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("gmc_report_url <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlLike(String value) {
            addCriterion("gmc_report_url like", value, "gmcReportUrl");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlNotLike(String value) {
            addCriterion("gmc_report_url not like", value, "gmcReportUrl");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlIn(List<String> values) {
            addCriterion("gmc_report_url in", values, "gmcReportUrl");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlNotIn(List<String> values) {
            addCriterion("gmc_report_url not in", values, "gmcReportUrl");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlBetween(String value1, String value2) {
            addCriterion("gmc_report_url between", value1, value2, "gmcReportUrl");
            return (Criteria) this;
        }

        public Criteria andGmcReportUrlNotBetween(String value1, String value2) {
            addCriterion("gmc_report_url not between", value1, value2, "gmcReportUrl");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreatedByEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("created_by = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreatedByNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("created_by <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreatedByGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("created_by > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreatedByGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("created_by >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreatedByLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("created_by < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreatedByLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("created_by <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIsNull() {
            addCriterion("last_update_by is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIsNotNull() {
            addCriterion("last_update_by is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByEqualTo(String value) {
            addCriterion("last_update_by =", value, "lastUpdateBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateByEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_by = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotEqualTo(String value) {
            addCriterion("last_update_by <>", value, "lastUpdateBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateByNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_by <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateByGreaterThan(String value) {
            addCriterion("last_update_by >", value, "lastUpdateBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateByGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_by > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("last_update_by >=", value, "lastUpdateBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateByGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_by >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLessThan(String value) {
            addCriterion("last_update_by <", value, "lastUpdateBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateByLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_by < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLessThanOrEqualTo(String value) {
            addCriterion("last_update_by <=", value, "lastUpdateBy");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateByLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_by <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLike(String value) {
            addCriterion("last_update_by like", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotLike(String value) {
            addCriterion("last_update_by not like", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIn(List<String> values) {
            addCriterion("last_update_by in", values, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotIn(List<String> values) {
            addCriterion("last_update_by not in", values, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByBetween(String value1, String value2) {
            addCriterion("last_update_by between", value1, value2, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotBetween(String value1, String value2) {
            addCriterion("last_update_by not between", value1, value2, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateTimeEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateTimeNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateTimeGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateTimeGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateTimeLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andLastUpdateTimeLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("last_update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCallCntIsNull() {
            addCriterion("call_cnt is null");
            return (Criteria) this;
        }

        public Criteria andCallCntIsNotNull() {
            addCriterion("call_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andCallCntEqualTo(Integer value) {
            addCriterion("call_cnt =", value, "callCnt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCallCntEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("call_cnt = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCallCntNotEqualTo(Integer value) {
            addCriterion("call_cnt <>", value, "callCnt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCallCntNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("call_cnt <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCallCntGreaterThan(Integer value) {
            addCriterion("call_cnt >", value, "callCnt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCallCntGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("call_cnt > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCallCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("call_cnt >=", value, "callCnt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCallCntGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("call_cnt >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCallCntLessThan(Integer value) {
            addCriterion("call_cnt <", value, "callCnt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCallCntLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("call_cnt < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCallCntLessThanOrEqualTo(Integer value) {
            addCriterion("call_cnt <=", value, "callCnt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andCallCntLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("call_cnt <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCallCntIn(List<Integer> values) {
            addCriterion("call_cnt in", values, "callCnt");
            return (Criteria) this;
        }

        public Criteria andCallCntNotIn(List<Integer> values) {
            addCriterion("call_cnt not in", values, "callCnt");
            return (Criteria) this;
        }

        public Criteria andCallCntBetween(Integer value1, Integer value2) {
            addCriterion("call_cnt between", value1, value2, "callCnt");
            return (Criteria) this;
        }

        public Criteria andCallCntNotBetween(Integer value1, Integer value2) {
            addCriterion("call_cnt not between", value1, value2, "callCnt");
            return (Criteria) this;
        }

        public Criteria andStsCdIsNull() {
            addCriterion("sts_cd is null");
            return (Criteria) this;
        }

        public Criteria andStsCdIsNotNull() {
            addCriterion("sts_cd is not null");
            return (Criteria) this;
        }

        public Criteria andStsCdEqualTo(String value) {
            addCriterion("sts_cd =", value, "stsCd");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andStsCdEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sts_cd = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStsCdNotEqualTo(String value) {
            addCriterion("sts_cd <>", value, "stsCd");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andStsCdNotEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sts_cd <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStsCdGreaterThan(String value) {
            addCriterion("sts_cd >", value, "stsCd");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andStsCdGreaterThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sts_cd > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStsCdGreaterThanOrEqualTo(String value) {
            addCriterion("sts_cd >=", value, "stsCd");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andStsCdGreaterThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sts_cd >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStsCdLessThan(String value) {
            addCriterion("sts_cd <", value, "stsCd");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andStsCdLessThanColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sts_cd < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStsCdLessThanOrEqualTo(String value) {
            addCriterion("sts_cd <=", value, "stsCd");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria andStsCdLessThanOrEqualToColumn(ManManufacturer.Column column) {
            addCriterion(new StringBuilder("sts_cd <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStsCdLike(String value) {
            addCriterion("sts_cd like", value, "stsCd");
            return (Criteria) this;
        }

        public Criteria andStsCdNotLike(String value) {
            addCriterion("sts_cd not like", value, "stsCd");
            return (Criteria) this;
        }

        public Criteria andStsCdIn(List<String> values) {
            addCriterion("sts_cd in", values, "stsCd");
            return (Criteria) this;
        }

        public Criteria andStsCdNotIn(List<String> values) {
            addCriterion("sts_cd not in", values, "stsCd");
            return (Criteria) this;
        }

        public Criteria andStsCdBetween(String value1, String value2) {
            addCriterion("sts_cd between", value1, value2, "stsCd");
            return (Criteria) this;
        }

        public Criteria andStsCdNotBetween(String value1, String value2) {
            addCriterion("sts_cd not between", value1, value2, "stsCd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table man_manufacturer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        private ManManufacturerExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        protected Criteria(ManManufacturerExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public ManManufacturerExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table man_manufacturer
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table man_manufacturer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table man_manufacturer
         *
         * @mbg.generated
         */
        void example(neu.train.project.mvo.domain.ManManufacturerExample example);
    }
}