package neu.train.project.mvo.mapper;

import neu.train.project.mvo.domain.BrdBrand;
import neu.train.project.mvo.domain.BrdBrandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BrdBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    long countByExample(BrdBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int deleteByExample(BrdBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer brdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int insert(BrdBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int insertSelective(BrdBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    BrdBrand selectOneByExample(BrdBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    BrdBrand selectOneByExampleSelective(@Param("example") BrdBrandExample example, @Param("selective") BrdBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    List<BrdBrand> selectByExampleSelective(@Param("example") BrdBrandExample example, @Param("selective") BrdBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    List<BrdBrand> selectByExample(BrdBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    BrdBrand selectByPrimaryKeySelective(@Param("brdId") Integer brdId, @Param("selective") BrdBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    BrdBrand selectByPrimaryKey(Integer brdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    BrdBrand selectByPrimaryKeyWithLogicalDelete(@Param("brdId") Integer brdId, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BrdBrand record, @Param("example") BrdBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BrdBrand record, @Param("example") BrdBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BrdBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BrdBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") BrdBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brd_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer brdId);
}