package neu.train.project.mvo.mapper;

import java.util.List;
import neu.train.project.mvo.domain.PckPackageInfo;
import neu.train.project.mvo.domain.PckPackageInfoExample;
import org.apache.ibatis.annotations.Param;

public interface PckPackageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    long countByExample(PckPackageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int deleteByExample(PckPackageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int insert(PckPackageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int insertSelective(PckPackageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    PckPackageInfo selectOneByExample(PckPackageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    PckPackageInfo selectOneByExampleSelective(@Param("example") PckPackageInfoExample example, @Param("selective") PckPackageInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    List<PckPackageInfo> selectByExampleSelective(@Param("example") PckPackageInfoExample example, @Param("selective") PckPackageInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    List<PckPackageInfo> selectByExample(PckPackageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    PckPackageInfo selectByPrimaryKeySelective(@Param("pckId") Integer pckId, @Param("selective") PckPackageInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    PckPackageInfo selectByPrimaryKey(Integer pckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PckPackageInfo record, @Param("example") PckPackageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PckPackageInfo record, @Param("example") PckPackageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PckPackageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PckPackageInfo record);
}