package neu.train.project.mvo.mapper;

import java.util.List;
import neu.train.project.mvo.domain.PrcProductCategory;
import neu.train.project.mvo.domain.PrcProductCategoryExample;
import org.apache.ibatis.annotations.Param;

public interface PrcProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    long countByExample(PrcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int deleteByExample(PrcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer prcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int insert(PrcProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int insertSelective(PrcProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    PrcProductCategory selectOneByExample(PrcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    PrcProductCategory selectOneByExampleSelective(@Param("example") PrcProductCategoryExample example, @Param("selective") PrcProductCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    List<PrcProductCategory> selectByExampleSelective(@Param("example") PrcProductCategoryExample example, @Param("selective") PrcProductCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    List<PrcProductCategory> selectByExample(PrcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    PrcProductCategory selectByPrimaryKeySelective(@Param("prcId") Integer prcId, @Param("selective") PrcProductCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    PrcProductCategory selectByPrimaryKey(Integer prcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    PrcProductCategory selectByPrimaryKeyWithLogicalDelete(@Param("prcId") Integer prcId, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PrcProductCategory record, @Param("example") PrcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PrcProductCategory record, @Param("example") PrcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PrcProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PrcProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") PrcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer prcId);
}